name: pidl
description: plugin idl compiler
version: 1.0.0
publish_to: none

# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.0.0
  path: ^1.8.0
  meta: ^1.3.0
  collection: ^1.1.0  
  # petitparser: 
  #   path: ../third_party/petitparser
  darq: ^1.2.1
  
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
